# Generated by Django 3.2.2 on 2021-05-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentGatewayIntegration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='capture_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
